
name: Build Windows Executable

on:
  workflow_dispatch
  # Uncomment below if you want to build on push to main branch
  # push:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest  # Changed to Windows runner

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc
    
    - name: Install dependencies
      run: |
        # Add any dependency installation commands here if needed
        # For example, if you need MSVC build tools or other libraries
    
    - name: Build Release
      run: cargo build --release --verbose
    
    - name: Run tests
      run: cargo test --release --verbose
    
    - name: Package Application
      run: |
        mkdir package
        cp target/release/ytdlp-gui.exe package/
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ytdlp-gui-windows
        path: package/
